server:
  port: 9082
  servlet:
    context-path: /app
spring:
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:./src/main/resources/productDB;MODE=PostgreSQL
#    url: jdbc:h2:~/productDB;MODE=PostgreSQL
    url: jdbc:h2:mem:productDB;MODE=PostgreSQL
    username: admin
    password:
  jpa:
    show-sql: true
    properties:
      hibertnate:
        dialect: org.hibernate.dialect.H2Dialec
  h2:
    console:
      enabled: true
      path: /h2