DROP TABLE IF EXISTS carts CASCADE;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS products CASCADE;

CREATE TABLE IF NOT EXISTS products (ID bigserial NOT NULL, TITLE varchar(255) NOT NULL, PRICE real NOT NULL DEFAULT 0.55, COUNT integer DEFAULT  1, PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS users (ID bigserial NOT NULL, LOGIN varchar(255) NOT NULL, PASSWORD varchar(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS carts (USER_ID integer, PRODUCT_ID integer, FOREIGN KEY (USER_ID) REFERENCES users(ID), FOREIGN KEY (PRODUCT_ID) REFERENCES products(ID));

INSERT INTO products (TITLE, PRICE) VALUES ('Milk', 1.05),('Eggs', 2.15),('Nuts', 4.09),('Beer', 3.12),('Fish', 2.78),('Ice cream', 0.99),('Curd cheese', 0.83);
INSERT INTO users(LOGIN, PASSWORD) VALUES ('admin', 'admin');
